# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven CI

on:
  push:
    branches: [ hikari, cleanup ]
  pull_request:
    branches: [ hikari, cleanup ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn package --batch-mode --update-snapshots -T 1.5C -f pom.xml -P github
      - uses: actions/upload-artifact@v3
        with:
          name: quickshop-snapshots
          path: |
            **/target/*.jar
