# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: mc-publish

on:
  workflow_dispatch:
  release:
    types:
      - published
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package -T 1.5C --file pom.xml
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ijC5dDkD
          modrinth-featured: true
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          github-discussion: Announcements
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-draft: false
          files: |
            quickshop-bukkit/target/QuickShop-Hikari-*.jar
            **/target/+(Compat*|Addon*).jar
          loaders: |
            spigot
            paper
            purpur
          game-versions: |
            >=1.18.2 <=1.20.4
          game-version-filter: releases
          java: |
            17
          dependencies: |
            essentialsx(optional)
            nbtapi(optional)
            discordsrv(optional)
            bluemap(optional)
            dynmap(optional)
            worldedit(optional)
            worldguard(optional)
            plan(optional)
            bentobox(optional)
            clearlag(optional)
            elitemobs(optional)
            griefprevention(optional)
            lands(optional)
            openinv(optional)
            placeholderapi(optional)
            residence(optional)
            towny(optional)
            superiorskyblock(optional)
            luckperms(optional)
            vault(optional)
            plan(optional)
            advancedregionmarket(optional)
            ecoenchants(optional)
            reforges(optional)
            packetlistenerapi(conflicting)
      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      - name: Build Translations
        uses: Ghost-chu/CrowdinCopyDeploy-action@master
        with:
          args: uploads3
        env:
          CROWDIN_ACCESS_TOKEN: ${{ secrets.CROWDIN_ACCESS_TOKEN }}
          CROWDIN_PROJECT_BRANCH_ID: '126'
          CROWDIN_PROJECT_ID: '524354'
          #DEPLOY_PATH: './deploy-prod'
          AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: auto
      - name: Purge CloudFlare cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          # Zone is required by both authentication methods
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
