# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: mc-publish

on:
  workflow_dispatch:
  release:
     types:
       - published
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -T 16 --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
    - uses: Kir-Antipov/mc-publish@v3.2
      with:
        modrinth-id: ijC5dDkD
        modrinth-featured: true
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        modrinth-dependencies: |
          hXiIvTyT | recommends | *
          nfGCP9fk | recommends | *

        github-discussion: Announcements
        github-token: ${{ secrets.GITHUB_TOKEN }}
        github-draft: false
        
        #curseforge-id: 709851
        #curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
        #curseforge-name: QuickShop-Hikari
        #curseforge-dependencies: |
        #  vault | depends | *
        #  protocollib | recommends | *
        #  essentialsx | recommends | *
        #  worldedit | recommends | *
        #  nbt-api | recommends | *
        
        files-primary: "quickshop-bukkit/target/QuickShop-Hikari-*.jar"
        files-secondary: "**/target/Compat-*.jar"
        loaders: |
         spigot
         paper
         purpur
        game-versions: |
          1.18.2
          1.19
          1.19.1
          1.19.2
        java: |
          17
